---
- name: restart k3s
  service:
    name: k3s
    state: restarted

- name: fix kubeconfig perms
  file:
    path: /etc/rancher/k3s/k3s.yaml
    state: file
    owner: root
    group: "{{ kubeconfig_group | default('kube') }}"
    mode: "0640"
