---
- name: Apply PSS enforced namespace
  tags: [kube]
  command: kubectl apply -f pss-restricted-namespace.yaml
  args:
    chdir: "{{ role_path }}/files"


- name: Apply default deny NetworkPolicy
  tags: [kube]
  command: kubectl apply -f netpol-deny-all.yaml
  args:
    chdir: "{{ role_path }}/files"