---
- name: Ensure base packages
  tags: [base]
  apt:
  name:
  - unattended-upgrades
  - ufw
  - fail2ban
  - curl
  - jq
  - lsof
  state: present
  update_cache: true


- name: Enable unattended upgrades
  tags: [base]
  debconf:
  name: unattended-upgrades
  question: unattended-upgrades/enable_auto_updates
  value: "true"
  vtype: boolean