---
- name: Reset UFW to known state
  tags: [ufw]
  command: ufw --force reset

- name: Set default incoming policy to deny
  tags: [ufw]
  ufw:
    direction: incoming
    policy: deny

- name: Set default outgoing policy to allow
  tags: [ufw]
  ufw:
    direction: outgoing
    policy: allow

- name: Ensure UFW is enabled
  tags: [ufw]
  ufw:
    state: enabled

- name: Allow SSH from LAN
  tags: [ufw]
  ufw:
    rule: allow
    proto: tcp
    port: "{{ ssh_port }}"
    src: "{{ lan_cidr }}"

- name: Allow k3s API from LAN (masters only)
  tags: [ufw]
  when: "'masters' in group_names"
  ufw:
    rule: allow
    proto: tcp
    port: "6443"
    src: "{{ lan_cidr }}"

# mDNS: keep it simple—allow UDP/5353 both directions (covers multicast use-case)
- name: Allow mDNS if enabled (inbound UDP/5353)
  tags: [ufw]
  when: enable_mdns | default(false)
  ufw:
    rule: allow
    proto: udp
    port: "5353"

- name: Allow mDNS if enabled (outbound UDP/5353)
  tags: [ufw]
  when: enable_mdns | default(false)
  ufw:
    rule: allow
    proto: udp
    port: "5353"
  # outbound is already allowed by default; this is explicit/harmless

- name: Show UFW status
  tags: [ufw]
  command: ufw status verbose
  register: ufw_status
  changed_when: false

- name: Print UFW status
  tags: [ufw]
  debug:
    var: ufw_status.stdout_lines
