---
- name: Reset UFW to known state
  tags: [ufw]
  command: ufw --force reset

- name: Set default incoming policy to deny
  tags: [ufw]
  ufw:
    direction: incoming
    policy: deny

- name: Set default outgoing policy to allow
  tags: [ufw]
  ufw:
    direction: outgoing
    policy: allow

- name: Ensure UFW is enabled
  tags: [ufw]
  ufw:
    state: enabled

- name: Allow SSH from LAN
  tags: [ufw]
  ufw:
    rule: allow
    proto: tcp
    port: "{{ ssh_port }}"
    src: "{{ lan_cidr }}"

- name: Allow k3s API from LAN (masters only)
  tags: [ufw]
  when: "'masters' in group_names"
  ufw:
    rule: allow
    proto: tcp
    port: "6443"
    src: "{{ lan_cidr }}"

# mDNS: keep it simple—allow UDP/5353 both directions (covers multicast use-case)
- name: Allow mDNS if enabled (inbound UDP/5353)
  tags: [ufw]
  when: enable_mdns | default(false)
  ufw:
    rule: allow
    proto: udp
    port: "5353"

- name: Allow mDNS if enabled (outbound UDP/5353)
  tags: [ufw]
  when: enable_mdns | default(false)
  ufw:
    rule: allow
    proto: udp
    port: "5353"
  # outbound is already allowed by default; this is explicit/harmless

- name: Allow etcd client (2379) from LAN (masters only)
  tags: [ufw]
  when: "'masters' in group_names"
  ufw:
    rule: allow
    proto: tcp
    port: "2379"
    src: "{{ lan_cidr }}"

- name: Allow etcd peer (2380) from LAN (masters only)
  tags: [ufw]
  when: "'masters' in group_names"
  ufw:
    rule: allow
    proto: tcp
    port: "2380"
    src: "{{ lan_cidr }}"

- name: Allow k3s supervisor (9345) from LAN (masters only)
  tags: [ufw]
  when: "'masters' in group_names"
  ufw:
    rule: allow
    proto: tcp
    port: "9345"
    src: "{{ lan_cidr }}"

- name: Allow Flannel VXLAN (8472/udp) between nodes
  tags: [ufw]
  ufw:
    rule: allow
    proto: udp
    port: "8472"
    src: "{{ lan_cidr }}"

- name: Ensure forward policy ACCEPT
  tags: [ufw]
  lineinfile:
    path: /etc/default/ufw
    regexp: '^DEFAULT_FORWARD_POLICY='
    line: 'DEFAULT_FORWARD_POLICY="ACCEPT"'

- name: Allow overlay interface traffic (flannel in/out)
  tags: [ufw]
  ufw: { rule: allow, interface: "flannel.1", direction: in }
- name: Allow overlay interface traffic (flannel out)
  tags: [ufw]
  ufw: { rule: allow, interface: "flannel.1", direction: out }

- name: Allow CNI bridge traffic (cni0 in/out)
  tags: [ufw]
  ufw: { rule: allow, interface: "cni0", direction: in }
- name: Allow CNI bridge traffic (cni0 out)
  tags: [ufw]
  ufw: { rule: allow, interface: "cni0", direction: out }

- name: Allow kubelet 10250 from pod CIDR
  tags: [ufw]
  ufw:
    rule: allow
    proto: tcp
    port: "10250"
    src: "10.42.0.0/16"

- name: Show UFW status
  tags: [ufw]
  command: ufw status verbose
  register: ufw_status
  changed_when: false

- name: Print UFW status
  tags: [ufw]
  debug:
    var: ufw_status.stdout_lines
