---
- name: Create required directories (masters only)
  tags: [k3s]
  file:
  path: "{{ item }}"
  state: directory
  mode: "0755"
  loop:
    - /etc/rancher/k3s
    - /var/lib/rancher/k3s/server/logs
    - /etc/kubernetes/audit
  when: "'masters' in group_names"


- name: Deploy k3s config (masters only)
  tags: [k3s]
  template:
  src: k3s_config.yaml.j2
  dest: /etc/rancher/k3s/config.yaml
  when: "'masters' in group_names"


- name: Minimal audit policy (masters only, when enabled)
  tags: [k3s]
  copy:
  dest: /etc/kubernetes/audit/policy.yaml
  content: |
  apiVersion: audit.k8s.io/v1
  kind: Policy
  rules:
- level: Metadata
  when: "'masters' in group_names and enable_k3s_audit"


- name: Reload systemd and restart k3s if present (masters only)
  tags: [k3s]
  shell: |
    systemctl daemon-reload || true
    systemctl restart k3s || true
  when: "'masters' in group_names"